Section "Device"
Identifier "LCD"
Driver "fbdev"
Option "fbdev" "/dev/fb_mhs"
EndSection

Section "Screen"
Identifier "Screen0"
Device "LCD"
EndSection

Section "ServerLayout"
Identifier "Layout0"
Screen 0 "Screen0"
EndSection